### ISSUE TITLE
Desktop screenshot of rk-qt-video video is black 

### ISSUE THREAD

**Issue by radojko** [Miouyouyou/MyyQi#10]
Capturing desktop with scrot when playing video with rk-qt-video on glamor is black.

**Comment by Miouyouyou** [comment]
1. Does this problem occurs with official Rockchip kernels too ?
2. I don't think this is related to kernels. For Rockchip tools issues, I highly suggest to try the following places :
https://github.com/rockchip-linux/xserver
https://github.com/rockchip-linux/gstreamer-rockchip
or
https://github.com/rockchip-linux/buildroot
3. If this related to the kernel, I would suggest to retry with a [RockMyy patchset](https://github.com/Miouyouyou/RockMyy), which compiles mainline 4.17-rcX kernels. The 4.13 MyyQi patchset is currently not maintained.

**Comment by radojko** [comment]
Ok, thanks!
